src/observer/storage/common/bplus_tree.cpp

speed up the lookup

---

CMakeLists.txt

unittest: optional dependency

---

README.md

fix a typo in markdown

---

deps/common/seda/seda_config.cpp
deps/common/seda/thread_pool.cpp
deps/common/seda/timer_stage.cpp

增加线程名称，便于调试。

---

deps/common/seda/seda_config.cpp
deps/common/seda/thread_pool.cpp
deps/common/seda/timer_stage.cpp
test/perf/client_performance_test.cpp

fix issue 'client_performance_test' failed

---

.gitmodules
docs/how_to_build.md

将.gitmodules集成在项目里面，同时去掉how_to_build.md中的git submodule add，用更标准化的方式使用git，同时为后续一键安装脚本提供便利条件。

简化git submodule操作，标准化git使用

---

src/observer/storage/default/default_storage_stage.cpp

修复load data读取文件时去掉空白字符的问题

---

src/observer/sql/expr/tuple_cell.cpp
src/observer/util/util.cpp
src/observer/util/util.h

增加浮点数打印的函数，此函数输出的结果与测试环境要求的保持一直：
最多保留两位小数；
四舍五入；
去掉多余的0

add float print function

---

docs/miniob_topics.md

Update problem specification for select-meta.

add comments for select-meta

---

README.md

Closes #128, rewrite readme

---

.gitpod.yml
README.md

Issue Number: close #146
Problem:

add gitpod support

---

.github/workflows/build.yml

github build action adds support for mac system
#157 
Problem:
added ci/cd support for Mac

added github ci/cd build support for mac

---

.github/workflows/build.yml
CMakeLists.txt
src/observer/storage/clog/clog.cpp
src/observer/storage/record/record_manager.cpp
unittest/CMakeLists.txt
unittest/bp_manager_test.cpp
unittest/clog_test.cpp

fix unittest;
add unittest to github action
Issue Number: close #176 close #163 
Problem:
单元测试执行失败；
github action 没有单元测试检查

fix unittest (#9)

---

.clang-format
benchmark/bplus_tree_concurrency_test.cpp
benchmark/integer_generator.h
benchmark/record_manager_concurrency_test.cpp
benchmark/server_concurrency_test.cpp

Issue Number: ref #164 
Problem:
使用clang-format格式化benchmark模块代码

format benchmark codes

---

.github/workflows/jekyll-gh-pages.yml
.gitignore
README.md

Issue Number: close #188 
Problem:
利用doxygen将代码注释生成文档
修改github action，增加doxygen生成文档，并gihtub pages部署发布

doxygen 文档

---

.github/workflows/jekyll-gh-pages.yml
.gitignore
README.md
src/observer/sql/operator/insert_physical_operator.cpp
src/observer/sql/operator/table_scan_physical_operator.cpp
src/observer/sql/optimizer/optimize_stage.cpp
src/observer/sql/optimizer/physical_plan_generator.cpp
src/observer/sql/parser/lex_sql.cpp
src/observer/sql/parser/lex_sql.h
src/observer/sql/parser/yacc_sql.cpp
src/observer/sql/parser/yacc_sql.y

Issue Number: close #192 
Problem:
clang 14编译失败
修复编译错误

修复clang 14 compile error

---

docs/src/miniob-introduction.md
src/observer/common/rc.h
src/observer/net/buffered_writer.cpp
src/observer/net/buffered_writer.h
src/observer/net/communicator.cpp
src/observer/net/communicator.h
src/observer/net/mysql_communicator.cpp
src/observer/net/mysql_communicator.h
src/observer/net/ring_buffer.cpp
src/observer/net/ring_buffer.h
src/observer/storage/index/bplus_tree.cpp
src/observer/storage/trx/trx.cpp
unittest/ring_buffer_test.cpp

Issue Number: close #151 
Problem:
当前在发送消息到客户端时，每个数据都会刷新socket buffer，效率很低
实现BufferedWriter，通过buffered writer将消息缓存在内存中，结果写完时或者buffer满时，才将结果真正的发送到客户端。

Network buffer

---

README.md

Issue Number: close #213 
Problem:

fixed #213, optimize README.md

---

src/observer/net/buffered_writer.cpp

Issue Number: close #217 
Problem:
compile error on gcc 12

fix compile on gcc 12

---

docs/src/how_to_build.md
docs/src/how_to_run.md
src/observer/storage/trx/mvcc_trx.cpp

Issue Number: ref #205 
Problem:
build failed on docker container
fix compile error

Docker build error

---

docker/Dockerfile

Update Dockerfile
Issue Number: #205
Problem:
1.  Use Ubuntu latest image
2.  Use dpes on ubuntu
3.  Do not prepare deps when docker compose, because now we have `build.sh init`

Use Ubuntu docker as base image

---

docs/book.toml
src/observer/sql/optimizer/logical_plan_generator.cpp
src/observer/sql/optimizer/logical_plan_generator.h
src/observer/sql/optimizer/optimize_stage.cpp
src/observer/sql/optimizer/optimize_stage.h

Issue Number: close #230 
Problem:
logical plan的生成代码全放在了optimize中，看起来很不清晰
将logical plan的代码提取出来放在logical plan generator中

refactor logical plan generator

---

src/observer/session/session_stage.cpp

fix: delete sql_event after use

---

deps/common/os/process.cpp

snprintf函数第二个参数应该为buf_len + 1

---

src/observer/event/session_event.cpp
src/observer/event/session_event.h
src/observer/event/sql_debug.cpp
src/observer/event/sql_debug.h
src/observer/event/sql_event.cpp
src/observer/event/sql_event.h
src/observer/event/storage_event.h
src/observer/net/buffered_writer.cpp
src/observer/net/buffered_writer.h
src/observer/net/cli_communicator.cpp
src/observer/net/cli_communicator.h
src/observer/net/communicator.cpp
src/observer/net/communicator.h
src/observer/net/mysql_communicator.cpp
src/observer/net/mysql_communicator.h
src/observer/net/plain_communicator.cpp
src/observer/net/plain_communicator.h
src/observer/net/ring_buffer.cpp
src/observer/net/ring_buffer.h
src/observer/net/server.cpp
src/observer/net/server.h
src/observer/net/server_param.h

Issue Number: ref #260 
clang-format

clang-format

---

build.sh

use latest libevent

---

.github/workflows/build.yml

Problem:
There is no unittest coverage information.
Build with -DENABLE_COVERAGE=ON.

collect coverage info

---

docs/src/SUMMARY.md
docs/src/design/introduction.md

Issue Number: close #337 
Problem:
add docs/src/design/miniob-mysql-protocol.md in the following documents to remake the mdbook to make the website in the docs/src/miniob-introduction.md correct.
> docs/src/SUMMARY.md
> docs/src/design/introduction.md

add the protocol.md in the summary.md

---

src/observer/storage/clog/clog.cpp
src/observer/storage/record/record_manager.cpp

@sa [easy_align](https://github.com/oceanbase/oceanbase/blob/develop/deps/easy/src/include/easy_define.h#L45)

Enhancement: make alignment easy

---

src/observer/storage/buffer/double_write_buffer.h

Issue Number: close #401 
some test ref: https://github.com/nautaa/miniob/actions/runs/9042145064
Problem:

fix DoubleWriteBuffer init

---

README.md
docs/docs/blog/1.md
docs/docs/game/introduction.md

修复文档中的一些链接

---

README.md

Issue Number: close #424
add hello github badge

add hellogithub badge

---

.github/workflows/pulish-docker-image.yml
docker/Dockerfile
docs/docs/dev-env/how-to-dev-using-docker.md

Problem:
docker.io is disabled in China.
Use another image repo instead.

publish docker image

---

docs/docs/dev-env/how-to-dev-using-docker.md

Problem:
docker.io 在国内被禁用了，把镜像推送到quay.io和ghcr.io中。

add source quay.io and ghcr.io

---

src/observer/storage/table/table.cpp

fix memory leak in Table::make_record

---

.github/workflows/test.yml
CMakeLists.txt

disable memtracer in default

---

src/observer/common/type/integer_type.cpp

Issue Number: close #450 
Problem:
See commit.

fix: undefined behavior in IntegerType::compare function (#450)

---

docs/docs/game/miniob-vectordb.md

fix cosine_distance docs

---

.github/workflows/build.yml
CMakeLists.txt
src/observer/sql/operator/explain_physical_operator.cpp
src/observer/sql/operator/explain_physical_operator.h

Issue Number: close #502 
Problem:

support ubuntu24.04

---

.github/workflows/gh-pages.yml

fix: github page deploy

---

docs/mkdocs.yml

fix docs display

---

docs/Doxyfile
docs/docs/db_course_lab/lab1.md

fix doxy display

---

.github/workflows/test.yml

add ci log for sysbench

---

unittest/oblsm/ob_skiplist_test.cpp

fix ob_skiplist_test

---

src/oblsm/table/ob_sstable.h

Issue Number: close #547 
Problem:

fix build error

---

docs/docs/db_course_lab/lab1.md
docs/docs/db_course_lab/lab2.md
docs/docs/db_course_lab/lab3.md
docs/docs/db_course_lab/lab4.md
docs/docs/db_course_lab/overview.md

improve docs

---

benchmark/oblsm_performance_test.cpp

fix oblsm perf
