oceanbase/miniob

src/observer/init.cpp
src/observer/storage/common/meta_util.h
src/observer/storage/common/record_manager.cpp
src/observer/storage/common/record_manager.h
src/observer/storage/common/table.cpp
src/observer/storage/common/table.h
src/observer/storage/default/default_handler.cpp
src/observer/storage/default/default_handler.h
src/observer/storage/default/disk_buffer_pool.cpp
src/observer/storage/default/disk_buffer_pool.h
src/observer/storage/index/bplus_tree.cpp
src/observer/storage/index/bplus_tree.h
src/observer/storage/index/bplus_tree_index.cpp
unitest/bp_manager_test.cpp
unitest/bplus_tree_test.cpp

重构disk buffer pool：
新增BufferPoolManager，管理所有的DiskBufferPool；
原有DiskBufferPool只处理一个文件，取消其中file_id的概念；
删除BPPageHandle，直接使用Frame；
BPManager更名BPFrameManager；
BPFileSubHeader改为BPFileHeader并直接放在DiskBufferPool中

重构buffer pool

---

deps/common/lang/defer.h
src/obclient/client.cpp

1. 修正defer的编译错误；
2. 没有readline的环境上输出prompt
fix https://github.com/oceanbase/miniob/issues/38

print prompt in client on platform without readline

---

src/obclient/client.cpp

This pr try to add a psql (postgresql cmd tool) exit cmd, just a try. In psql, exit cmd tools by using '\q'.
这个pr我想尝试增加一个pgsql命令行工具psql里的退出命令，在psql里，使用\q推出工具。

add a psql exit cmd for miniob

---

Dockerfile

修复Dockerfile中cmake的安装错误

---

deps/common/io/io.cpp
unitest/pidfile_test.cpp

配置ASAN过程中`make -j8`报heap buffer overflow
排查原因是用char* 构造string，会调用strlen计算char *对应字符串的长度，原字符串是动态通过realloc分配的内存，对C风格字符串的末尾位'\0'未分配内存或未初始化。
附一段重现代码
``` cpp
#include <cstddef>
#include <cstdlib>
#include <iostream>
using namespace std;
// g++ main.cpp -g -fsanitize=address -o main
void foo(char *&str) {
char *s = NULL;
size_t len = 9;
for (int i = 0; i < len; i++) {
s = (char *)realloc(s, i + 1);
s[i] = '0' + i;
}
// s = (char *)realloc(s, len + 1);
// s[len] = '\0';
str = s;
}
int main() {
char p[16] = {'\0'};
char *str = p;
cout << "before call foo: address of str = " << reinterpret_cast<void *>(str)
<< endl;
foo(str);
string s(str);
cout << " after call foo: address of str = " << reinterpret_cast<void *>(str)
<< endl;
cout << s << endl;
free(str);
return 0;
}
```

fixed heap-buffer-overflow

---

src/obclient/client.cpp

支持处理历史任务
需要系统提前安装readline，如果不安装不会生效。
与shell环境操作类似，可以使用上下箭头选择历史数据。
操作历史会记录在$HOME/.miniob.history文件中。
fix https://github.com/oceanbase/miniob/issues/113

add history

---

docs/how_to_build.md

Issue Number: close #89 close #154 
Problem:
how_to_build 文档中描述的编译内容缺少了benchmark，并且步骤过于繁琐。
使用build.sh为基础描述构建文档。

修正how_to_build文档

---

src/obclient/CMakeLists.txt

Issue Number: close #61 
Problem:
cmake 3.10 版本不支持 cmake_link_directories 命令，而且miniob也不需要
将 cmake_link_directories 相关代码删除，可以正常编译

remove cmake_link_directories in client/cmake

---

src/observer/storage/record/record_manager.cpp
src/observer/storage/record/record_manager.h

Issue Number: close #226
Problem:
记录管理部分中page_header_中record_capacity初始化有误，需要进行修正
由于record_capacity的计算并没有考虑8字节对齐，计算的是不对齐时页面下容纳的最大记录量。
但第一条记录偏移量first_record_offset需要8字节对齐，使得最后一条记录的数据可能会溢出页面。
如果溢出页面，则减少record_capacity数值
同时去掉了部分冗余或含义不清的函数，修改了上取整的计算表达式
完善了记录管理模块成员函数的注释

Fix problem that record may overflow the page

---

src/observer/storage/persist/persist.h

my gcc version:
```text
使用内建 specs。COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,objc,obj-c++ --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib …
```

fix: add missing header files

---

.clang-format

Issue Number: close https://github.com/oceanbase/miniob/issues/258
Problem:

style: add a rule to avoid formatting LOG_* macros

---

src/observer/storage/index/bplus_tree.cpp

Issue Number: close #270 
Problem: When the database is shut down, the index file header does not sync properly.
When the database is shut down，check header_dirty_ flag in BplusTreeHandler, if true, sync the index file.

fix shutdown database without sync index file header

---

src/observer/storage/record/record_manager.cpp

In the `next()` function of Operator, `record_handler_->get_record(record_page_handler_, &rid, readonly_, &current_record_)` may be invoked more than one time. In this case, `record_page_handler_` has inited, it will return `RC::RECORD_OPENNED`, and `get_record()` will be failed.
When `page_handler.init()` return `RC::RECORD_OPENNED`, return `page_handler.get_record()` in `RecordFileHandler`.

bugfix: fix get record failed when page_handler has inited

---

src/observer/sql/operator/explain_physical_operator.cpp

Problem: do not close child operator in ExplainPhysicalOperator
```
create table a (a int);
create index idx on a(a);
explain delete from a where a=1;
```
cause SegFault, because trying to close IndexScanPhysicalOperator, but not open
Just do not close child oper in `ExplainPhysicalOperator::close`

fix: do not close in ExplainPhysicalOperator

---

deps/common/lang/comparator.cpp

Problem: compare_int uses subtraction to determine the size of two integers, which may cause integer overflow and return incorrect results.
When v1 is -2147483648 and v2 is 1, return 2147483647. Returned incorrect result due to integer overflow
Use comparison operators instead of subtraction

fix: overflow

---

src/observer/net/plain_communicator.cpp

Problem:
sql-debug的消息没有发送最终的消息终结符，并且消息是在消息终结符发送后发送的。
消息终结符统一在write_result最后发送，其它函数不再发送

修复sql_debug没有发送消息终结符的问题

---

src/observer/sql/expr/tuple.h

Problem:NLJ里面会遍历多次右表，就会调用很多次open，在open当中就会调用set_schema，然后join的时候就会添加大量重复的field和value的tuple，后续的话会被select的字段给过滤掉，不影响正确性，但是进行了冗余存储
在set_schema当中，每次先将原本的数据clear掉

fix:修复了set_schema当中会因为多次调用open而添加重复数据的问题

---

src/observer/storage/trx/mvcc_trx.cpp

Issue Number: close #314 
mvcc模式下无法正确删除当前事务插入的记录
在trx.delete_record添加特判，如果是删除当前事务插入的记录，就直接调用delete_record,并且也不添加到operation_里面，同时清除operation里面的相关insert_operation,这样可以保证事务内、提交后、回滚后、都能正确执行，并且不影响垃圾回收

fix:修复了mvcc模式下无法正确删除由当前事务插入的记录

---

docs/src/how_to_build.md

Issue Number: close #255
Problem: 将 https://ask.oceanbase.com/t/topic/35604437/8 中的内容写入到 how_to_build.md 的FAQ章节中

Issue Number: close #255

---

deps/common/log/log.cpp
deps/common/log/log.h
docs/src/how_to_build.md

Issue Number: close #317 
Problem:

add a lock to make LOG_HEAD thread-safe #{317}

---

src/observer/net/cli_communicator.cpp

Issue Number: close #281
Problem: If start observer in cli mode, we cannot exit observer by Ctrl+C.
在待输入命令时按下Ctrl+C后，注意到日志中有这样的记录：
"[2023-12-04 11:20:30.830780 pid:5338 tid:7fcf688ee7c0 ctx:0 WARN: my_readline@cli_communicator.cpp:71] >> failed to read line: Interrupted system call"
结合“cli_communicator.cpp:71”代码，可以知道此时系统错误被捕捉到且记录在errno中（此时errno为4）。
故当fgets读到空字符串时，若errno==4，可判定此时用户按下了Ctrl+C，这与用户输入“exit”等退出命令是等效的，故可看为用户输入了“interrupted"，借用“bool is_exit_command(const char *cmd)”函数判断用户输入的命令是否是退出命令，即可实现类似于用户输入了“exit”等命令的退出效果。

Use Ctrl+C to exit observer in cli mode.

---

NOTICE
test/sysbench/miniob_common.lua
test/sysbench/miniob_insert.lua

Problem:
miniob uses sysbench as the concurrency testing tool but there is no sysbench liscence
add sysbench liscence

add sysbench liscence

---

docs/src/dev-env/introduction.md

Problem: In the introduction document of dev-env, the links of `手把手教你在windows上用docker和vscode配置环境` and `MiniOB 调试` are not correct.
Correct the link and it works now.

Update link in introduction of dev-env doc

---

deps/common/lang/bitmap.cpp

Issue Number: close #335 
Problem: the first set/unset bit was not found correctly.
now the first set/unset bit could be found correctly.

bug fix of bitmap find next bit(#335)

---

.devcontainer/devcontainer.json

Problem:
oceanbase/miniob 镜像中已经把需要的依赖都加上了，如果还需要其它依赖，应该调整miniob镜像。
而且在国内安装devcontainer features中描述的组件，特别慢。
删除devcontainer文件中features相关内容

remove features in devcontainer

---

src/obclient/client.cpp
src/observer/main.cpp

Problem:
While people are learning about miniob, they don't know the owner of the project.
Printing copyright information when starting observer and obclient.

print startup tips

---

src/observer/common/rc.h
src/observer/storage/buffer/disk_buffer_pool.cpp
src/observer/storage/buffer/disk_buffer_pool.h
src/observer/storage/buffer/page.h
src/observer/storage/db/db.cpp
src/observer/storage/db/db.h

Issue Number: close #334 
Problem:
实现double write buffer以解决页面的原子写入问题。

double write buffer 

---

src/observer/common/types.h

g++13 can't compile
Issue Number: #378 
Problem: no header included in types.h
add #include<stdint.h> or <cstdint>

Update types.h, add #include<stdint.h>

---

src/observer/storage/buffer/double_write_buffer.cpp
src/observer/storage/buffer/double_write_buffer.h
src/observer/storage/db/db.cpp

Issue Number: close #403
Problem:
当更新double write buffer中的页面时，数据没有写入到磁盘，导致下次在读取时，数据不是最新的。
在调用add_page时，也刷新文件到磁盘。
double write buffer 增加设计要求：保证内存和磁盘中的数据都是最新的，比buffer pool中的要新。

[double write buffer]write page into file in add_page

---

src/observer/storage/db/db.cpp

Issue Number: close #397 
Problem:There is a use-after-free problem occuring between line 205 and 207.
I changed the order in which "table" was deleted and "table->name()" was called.

commit-message:fix #{397},use-after-free problem

---

src/observer/storage/buffer/double_write_buffer.cpp

when clean DiskDoubleWriteBuffer::dblwr_pages_, it also need to mark the disk page invalid.
Problem:

fix double write buffer recovery

---

src/observer/storage/clog/log_file.cpp

Issue Number: close none
Problem: none
remove directory_status in src/observer/storage/clog/log_file.cpp, solve unused variable  error if use clang toolchain

fix:remove unused variable

---

CMakeLists.txt
build.sh
deps/common/CMakeLists.txt
deps/common/os/process.cpp
deps/common/time/datetime.cpp
src/observer/net/buffered_writer.cpp
src/observer/net/ring_buffer.h

Issue Number: close #453 
Problem: Compatibility issues when implementing miniob on system based on musl libc like alpine linux.
Install libexecinfo as musl libc not support this feature.
``` bash
bash build.sh musl
```
Turn on support at miniob/CMakeLists.txt#L25. Then build the project.
``` bash
bash build.sh
```
This fix initially aims for developing and building miniob in docker containers using alpine linux.
NO Address Sanitizer Support in This PR.

feat: support system base on musl libc

---

src/observer/sql/expr/tuple.h

**Problem:**
When I attempted to join multiple tables, `libsanitizer` detected a memory leak. The error log is as follows:
```
==23682==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 768 byte(s) in 12 object(s) allocated from:
#0 0x75f738946a2a in operator new(unsigned long) /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_new_delete.cpp:95
#1 0x56870207d56f in RowTuple::set_schema(Table const*, std::vector<FieldMeta, std::allocator<FieldMeta> > const*) /home/pepefloyd/git/miniob/src/observer/sql/expr/tuple.h:184
#2 0x56870208f737 in TableScanPhysicalOperator::open(Trx*) /home/pepefloyd/git/miniob/src/observer/sql/operator/table_scan_physical_operator.cpp:25
#3 0x568702081888 in NestedLoopJoinPhysicalOperator::right_next() …
```

fix memory leak in RowTuple::set_schema

---

src/observer/storage/buffer/frame.cpp

在 Frame 类中，开启 DEBUG 模式下，如果同一个线程对同一个页面多次加读锁，read_lockers_  中的计数就无法被清除了，这会导致 ASSERT 失败。
我添加了以下逻辑：
在 Frame::read_unlatch 方法中，当 recursive_count != 1 时，将 read_lockers_ 中该线程的计数减一

修复 Frame 被同一线程多次加读锁后锁无法释放的 BUG

---

docs/docs/game/miniob-vectordb.md

preview link: https://nauta.com.cn/miniob/game/miniob-vectordb/#_4
Problem:

fix mkdocs display

---

src/observer/sql/parser/lex_sql.cpp
src/observer/sql/parser/lex_sql.h
src/observer/sql/parser/lex_sql.l

在`lex_sql.l`中，`WHITE_SPACE`被写成了`WHITE_SAPCE`

fix typo in lex_sql.l

---

deps/common/log/backtrace.cpp
docker/Dockerfile

Issue Number: #480 
Problem: 将docker的Ubuntu版本从22.04更新到24.04，检查了兼容性
- Dockerfile 中修改了部分容器构建过程
- /miniob/deps/common/log/backtrace.cpp 中添加了缺少的头文件

将docker版本从22.04更新为24.04

---

CONTRIBUTING.md

修改了因之前项目结构发生改变而无法跳转的链接
Issue Number: close #491

修改文件链接#491

---

.github/workflows/build.yml
.github/workflows/clang-format.yml
.github/workflows/codeql.yml
.github/workflows/gh-pages.yml
.github/workflows/pulish-docker-image.yml
.github/workflows/test.yml

Problem:
github action 中checkout代码的action很多使用的是v2，有时候github会发出告警。
使用最新版本 checkout@v4替换

github action中使用checkout v4替换旧版本

---

src/observer/storage/common/column.cpp

Issue Number: close #527 
Problem:
The `Column::append` function had a potential integer overflow issue when multiplying count and attr_len_. If these values were large, the multiplication could overflow, leading to undefined behavior. 
- The multiplication of `count` and `attr_len_` is now performed using `size_t`, a larger integer type, to avoid overflow.
- By using `size_t` for the multiplication, the risk of overflow is significantly reduced.

Fix: Multiplication result converted to larger type

---

unittest/oblsm/ob_compaction_test.cpp

In MiniOB, a `key` consists of an `internal key` followed by a `seq` component. When checking for overlapping keys in a sorted run, we should sort and compare based on the `internal key` only. This is typically done by using the `internal key` as the sorting index and then comparing the last key of the previous SSTable with the first key of the current one.
However, if the full `key` (including `seq`) is used as the sorting index, the `seq` component will incorrectly influence the result of the overlap check, potentially leading to false negatives or positives.
This PR replaces direct string comparison with the `obInternalKeyComparator` to sort and compare keys correctly, ensuring that only the `internal key` is considered during overlap checks.

fix bug about comparing key in ob_compaction_test

---

src/observer/storage/buffer/disk_buffer_pool.h
src/observer/storage/buffer/page.h

Issue Number: close #563
Problem:
This PR addresses two inconsistencies in the buffer pool page layout calculations:
1. Fix `MAX_PAGE_NUM` Calculation in `BPFileHeader`
From: 
```cpp
static const int MAX_PAGE_NUM = (BP_PAGE_DATA_SIZE - sizeof(page_count) - sizeof(allocated_pages)) * 8;
```
To:
```cpp
static const int MAX_PAGE_NUM = (BP_PAGE_DATA_SIZE - sizeof(buffer_pool_id) - sizeof(page_count) - sizeof(allocated_pages)) * 8;
```
2. Fix `BP_PAGE_DATA_SIZE` in `page.h`
From: 
```cpp
static constexpr const int BP_PAGE_DATA_SIZE = (BP_PAGE_SIZE - sizeof(PageNum) - sizeof(LSN) - sizeof(CheckSum));
```
To:
```cpp
static constexpr const int BP_PAGE_DATA_SIZE = (BP_PAGE_SIZE - sizeof(LSN) - sizeof(CheckSum));
```

fix the calculation of BPFileHeader::MAX_PAGE_NUM and BP_PAGE_DATA_SIZE

---

docs/docs/db_course_lab/lab4.md

add python2/pip2 install documents

---

src/observer/storage/common/column.cpp
src/observer/storage/common/column.h

reset_data() only reset the count, but not the data. When processing the string-like value, the previous data will be cached, and they may interfere with the new value. So reset the data after the count in reset_data().
Problem:
After calling reset_data() of Column with string type, call append_value() with another Value(). As long as the attr_len_ > Value.size(), the previous data will be retained, and they may interfere with the newly one, as the reset_data() does not clear the actual data inside.
For example:
id
ida
idb
After calling reset_data() and then call append_value() with actual string "a", the column will be as follows:
ad(the char 'c' retains.)
(the following are invalid.)
reset_data() will clear the inside data actually, not only reset the count.

fix: semantic conflict of reset_data.

---

src/common/io/io.h

Problem:
Fixed type mismatch in getFileSize by unifying the use of int64_t in both declaration and implementation.

fix type mismatch in getFileSize function signature and implementation

---

src/observer/sql/expr/expression.cpp
unittest/observer/expression_test.cpp

In unit_test, the use of empty chunks in the ArithmeticExpr.get_column test resulted in no calculation results. Previously, the ValueExpr was modified to return at least one constant value, but it was found to be problematic. This time, the test case will be directly modified.
Problem:

Fix ArithmeticExpr.get_column in unit_test

---

build.sh

Fix libevent, jsoncpp compilation on mac shows that cmake version is too high.
Fix libevent, jsoncpp compilation on mac shows that cmake version is too high.

Fix libevent, jsoncpp compilation on mac shows that cmake version is too high

---

src/observer/storage/index/bplus_tree.cpp

Issue Number: Close #572
**Problem:**
Static analysis (codescan) flagged a potential issue where the result of a multiplication operation (`item_size() * num`) is implicitly converted to a larger type. This may lead to unexpected behavior or data loss on certain compilers or platforms due to integer overflow.
**Changes:**
- Explicitly cast the multiplication result to the correct target type before passing it to `span<const char>()`.
- Ensures type safety and avoids potential overflow or truncation.
**Before:**
```cpp
span<const char>(items, item_size() * num)
```
**After:**
```cpp
span<const char>(items, static_cast<size_t>(item_size()) * num)
```
This ensures that the result of the multiplication is treated as a size_t, which is the expected type.

[BUGFIX] fixed multiplication promotion to larger type in span size

---

docs/mkdocs.yml

Problem: math formulas cannot be displayed normally
Because `polyfill.io` is blocked
see: https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet/
use alicdn

fix(docs): math formulas cannot be displayed normally

---

src/observer/sql/optimizer/cascade/tasks/o_expr_task.cpp
src/observer/storage/buffer/double_write_buffer.cpp
src/observer/storage/common/codec.h

When compiling MiniOB with a newer version of GCC (I use 15.1.1), a series of compilation errors may occur. This is mainly because the new version of the compiler has stricter standards for header file inclusion and namespace usage.
Issue Number: close None
Problem:
Some source files use algorithm functions like `std::sort` or `std::for_each` but do not include the `<algorithm>` header file.
Added `#include <algorithm>` in all C++ source files that use `std::sort` and `std::for_each`.
Tests show that after applying these modifications, the project can be successfully compiled in the GCC 15.1.1 environment.

fix(build): support the latest version of gcc
